### ISSUE TITLE
Documentation Doesn't Look Right

### ISSUE THREAD

**Issue by douglasgreen** [fruux/sabre-uri#118]
The documentation at https://sabre.io/uri/usage/ doesn't look right.

1. The first example has a syntax error where there is a missing semicolon: `$new = '../hello'`
2. All of the examples declare `namespace Sabre\Uri;` when they should be doing `use Sabre\Uri;` instead.

**Comment by staabm** [comment]
thanks for noting. would be great if you could provide a fix in https://github.com/sabre-io/sabre.io

**Comment by douglasgreen** [comment]
OK, I created a [pull request](https://github.com/sabre-io/sabre.io/pull/167) with the fixes.
