### ISSUE TITLE
resolve() fatal error when $delta['path'] is null

### ISSUE THREAD

**Issue by awhale** [fruux/sabre-uri#15]
When there is no path on the $basePath parameter and no leading slash on the $newPath parameter, a fatal error is generated.

```php
<?php
require('vendor/autoload.php');
$path = \Sabre\Uri\resolve('http://www.mydomain.com', '#');
```

> Fatal error: Uncaught TypeError: strpos() expects parameter 1 to be string, null given in vendor/sabre/uri/lib/functions.php:59
Stack trace:
#0 vendor/sabre/uri/lib/functions.php(59): strpos(NULL, '/')

It is being caused by null being passed into strpos() at the first parameter with strict types enabled.

It could be resolved by casting or null coalescing the value to a string to mimic php5 behaviour, or throwing an exception if this is behaviour you do not want to support.

**Comment by evert** [comment]
Hi!

This might be the weirdest thing I've seen so far. I added a unittest which passed (don't pay attention to the failed build here, different reason).

But, when I slightly change the unitest to force it to fail, I your fatal error. I can't' explain it, I don't get it. Hopefully ill have some more info here soon

**Comment by evert** [comment]
Never mind, I was looking at it wrong! Only happens with a fragment that does't have a value
