### ISSUE TITLE
issue with parse

### ISSUE THREAD

**Issue by phrazer** [fruux/sabre-uri#55]
this works OK
$base = 'https://example.org';
$new = './help/../hello/';

echo Sabre\Uri\resolve($base, $new);
**returns https://example.org/hello/**

**but double or more corrupt url:**
$base = 'https://example.org';
$new = './help/../../hello/';

echo Sabre\Uri\resolve($base, $new);
**returns https://example.orghello/**

**Comment by evert** [comment]
Definitely a bug!

**Comment by phil-davis** [comment]
Fixed in release https://github.com/sabre-io/uri/releases/tag/2.2.2
