### ISSUE TITLE
Field "pass" not handled correctly

### ISSUE THREAD

**Issue by vojtagrec** [fruux/sabre-uri#64]
While using sabre/uri in a work project, I noticed an inconsistency. It looks almost like the author forgot about the "pass" field:

1. `parse()` does not include "pass" with null value if no password is found in the URI,
2. `build()` does not include "pass" in the string URI even when it's passed in the input data.

**Comment by evert** [comment]
This is by design, passwords in uris are deprecated since at least 2005: https://tools.ietf.org/html/rfc3986#section-3.2.1

**Comment by vojtagrec** [comment]
I see. So it makes sense to not always provide "pass" in `parse()` result.

Still, it's _deprecated,_ not _removed._ I find it inconsistent that `parse()` (and PHP's `parse_url()` too) will return "pass" when you throw an URI that contains password at it, yet `build()` will fail to build such URL.

If you mean the "by design", `parse()` should probably unset "pass" from the result.

**Comment by evert** [comment]
I would agree that consistency would be better, including removing the password from the responses. It's too risky of a cahnge to make at this point given that this is a popular library and that's been the behavior for so long. Removing it from the parse functions would definitely mean a new major version.

My take on 'deprecated' is, lets not build new software relying on this behavior. That's the position I took writing this library at least. When I started the first version of this, it was already considered a pretty bad idea to support this in urls; so I removed it to encourage best security practices.

**Comment by vojtagrec** [comment]
OK, I get it, closing the issue then. Thanks anyway.

To provide some context, we're using "password in URI" just in dev environment to allow easy access to testing instances of the site (by just sharing an URI, without the need to whitelist IPs or provide VPN access). It serves just to keep out possible random visitors and bots. It serves this purpose well (and I don't see any alternative that's as easy and "cheap").

**Comment by evert** [comment]
Not sure if this helps, but you have a few options

1. It sounds like everyone shares the same username/password of the dev environment. Effectively this is a 'secret url', so you could also just embed a hard-to-guess code in the url itself.
2. Give everyone a username and password. Typically they only have to enter it once, browsers will remember
