### ISSUE TITLE
Parsing Windows file:/// URIs is now broken

### ISSUE THREAD

**Issue by zobo** [fruux/sabre-uri#81]
I did a minor upgrade on https://github.com/zobo/php-language-server and and after spending hours on debugging why a whole lot of things stopped working realized that Release 2.2.3 with #71 changed how Windows file URIs are parsed.

Now instead of getting `path: C:/dir/...` we get `path: /C:/dir/...`.

I have looked into a few different issues here to figure out why this would be OK, but I'm sorry, this is a breaking change and should have been released under a new major version.

**Comment by phil-davis** [comment]
```
<?php
// 1 - a host and then a path that has a top dir that is named the letter C (not a Windows drive letter)
$x = "file://somehost/C/somedir/file.ext";
$y = parse_url($x);
var_dump($x);
var_dump($y);
// 2 - now add a ':' after the C - the path has a thing that looks like Windows drive letter
// but of course it could be someone that created a dir called 'C:' on their *nix system.
$x = "file://somehost/C:/somedir/file.ext";
$y = parse_url($x);
var_dump($x);
var_dump($y);
// 3 - remove the host (we want to reference a file in a path on the local system)
$x = "file:///C:/somedir/file.ext";
$y = parse_url($x);
var_dump($x);
var_dump($y);
// 4 - remove the slash in front of 'C:'
// that correctly acts as a host 'C' that has the ':' to seaprate the port, but no port is mentioned
$x = "file://C:/somedir/file.ext";
$y = parse_url($x);
var_dump($x);
var_dump($y);
```

```
$ php t.php
/home/phil/t.php:5:
string(34) "file://somehost/C/somedir/file.ext"
/home/phil/t.php:6:
array(3) {
  'scheme' =>
  string(4) "file"
  'host' =>
  string(8) "somehost"
  'path' =>
  string(19) "/C/somedir/file.ext"
}
/home/phil/t.php:11:
string(35) "file://somehost/C:/somedir/file.ext"
/home/phil/t.php:12:
array(3) {
  'scheme' =>
  string(4) "file"
  'host' =>
  string(8) "somehost"
  'path' =>
  string(20) "/C:/somedir/file.ext"
}
/home/phil/t.php:16:
string(27) "file:///C:/somedir/file.ext"
/home/phil/t.php:17:
array(2) {
  'scheme' =>
  string(4) "file"
  'path' =>
  string(19) "C:/somedir/file.ext"
}
/home/phil/t.php:22:
string(26) "file://C:/somedir/file.ext"
/home/phil/t.php:23:
array(3) {
  'scheme' =>
  string(4) "file"
  'host' =>
  string(1) "C"
  'path' =>
  string(17) "/somedir/file.ext"
}
```

**Comment by phil-davis** [comment]
The above is with PHP 7.4 and direct use of `parse_url`.

Example 3 is the "problem". All the other examples end up returning `path` with a leading `/`.

In particular, "file://somehost/C:/somedir/file.ext" gets parsed as host "somehost" and path "/C:/somedir/file.ext"

When just "somehost" is removed from the string, I fully expect that host becomes the empty string (or is not set at all) and path should remain the same. But in example 3, the leading "/" goes missing from `path`.

**Comment by phil-davis** [comment]
IMO that is a bug in PHP, and thus a bug in `sabre-io/uri` and the change fixes the bug.

All bug-fixes change behavior - previously incorrect behavior is corrected by a bug fix. So therefore every bug-fix should be a major version bump, in case someone's code depends on the previously incorrect behavior. And therefore there would be no point in having the semver patch numbering system.

Of course, in practice, we should try to balance out what seems to be an "innocuous" change in behavior to fix what seems to be an "obvious" bug - and call it a patch release. And try to hold back bug-fixes that change behavior in a way that people might have been depending on the existing "incorrect" behavior for "a long time".

**Comment by phil-davis** [comment]
My first question to anyone - is there general agreement that example 3 above is a bug? That `path` should have a leading `/` in that example?

If it is not actually a bug, then I need to revert the bug-fix!

If it is a bug, then we need to keep the fix. But I could revert it, make a 2.3.2 release without the fix, then apply the fix again and make a 3.0.0 release. Should I do that?

@staabm your thoughts?

**Comment by zobo** [comment]
I think some implementations will treat file:///X:/...  as a special case. Like .NET for example https://dotnetfiddle.net/lIMLo0 others will not https://go.dev/play/p/I8ekrHTEUkB

I bet al lot was written about it, like this for example: https://github.com/golang/go/issues/6027#issuecomment-66083310 

Node has a function that will produce "expected" results, but specifically for paths https://nodejs.org/api/url.html#urlfileurltopathurl

I've bumped into similar problems before https://bugs.xdebug.org/view.php?id=1964

All in all, the change is probably correct and native PHP behaves wrong. I was just bothered that this happened on a patch level version change. But what's done is done, it would probably be worse to revert it now.

I would however suggest that this be explicitly noted in README, where the clame is:
> 3. parse, which works like PHP's [parse_url](http://php.net/manual/en/function.parse-url.php).

**Comment by staabm** [comment]
> If it is a bug, then we need to keep the fix. But I could revert it, make a 2.3.2 release without the fix, then apply the fix again and make a 3.0.0 release. Should I do that?

I guess this would be the easiest course of action.

I cannot judge whether the new behaviour is more correct then the old one.

**Comment by phil-davis** [comment]
> I  guess this would be the easiest course of action.

I made PR #83

**Comment by phil-davis** [comment]
This was "fixed" in https://github.com/sabre-io/uri/releases/tag/2.2.4 and https://github.com/sabre-io/uri/releases/tag/2.3.2 releases on 2022-09-19 - that preserves the previous behavior for the 2.* releases.

Major version https://github.com/sabre-io/uri/releases/tag/3.0.0 was released on 2022-09-26 with the breaking change.
