### ISSUE TITLE
Colon ':' in urls causing problems

### ISSUE THREAD

**Issue by sii** [fruux/sabre-uri#9]
Relating to this issue:
https://github.com/owncloud/core/issues/23740

Tested on php 7.0.4 on Ubuntu 16.04.

The parse function in lib/functions.php has trouble with colon characters in the wrong place in the uri.
The parse function in turn uses php's parse_url function which is what is failing under certain (odd) circumstances.

If there is a colon character as the second to last character in a uri phps parse_url function fails to parse the uri. When phps parse_url function fails and returns false, sabres parse function also fails.
It's also worth noting that phps parse_url works if you move the colon anywhere else in the string.

Here's how this can be reproduced:

`<?php`
`print "Works:\n";`
`var_dump(parse_url('/webdav/test3'));`
`print "\nFails:\n";`
`var_dump(parse_url('/webdav/test:3'));`
`?>`

I'm not sure how or where this is most appropriate to fix.

Thanks

**Comment by evert** [comment]
Hi!

Could you log in this as a php bug? If they acknowledge it we can think of building a workaround.

**Comment by evert** [comment]
I think part of the problem is that `:3` is probably being picked up as a port. Changing `3` to `a` cause it to succeed.

I think the fact that it starts with a `/` should have caused `parse_url` to have picked this up as a relative reference though, because `/` is not allowed in a uri scheme anyway.

**Comment by e-alfred** [comment]
Will this bug be solved anytime soon? Projects like Owncloud are still being affected by this:

https://github.com/owncloud/core/issues/23740

**Comment by staabm** [comment]
@e-alfred feel free to provide a unit test and bugfix

**Comment by evert** [comment]
The earlier comments still stand. Bug report to the php project would be a great first start.

**Comment by e-alfred** [comment]
Here is a bug report about it: https://bugs.php.net/bug.php?id=55511

They say it is not a bug on their side.

From https://github.com/owncloud/core/issues/25479.

**Comment by staabm** [comment]
sounds like a colon needs to be encoded when part of the url-path

**Comment by PVince81** [comment]
but then it was said that the spec was superseded and it doesn't need to be encoded any more: 

> The quoted spec has been superseded by RFC 3986 and that does allow colons in the path.

**Comment by PVince81** [comment]
@evert wait for a PHP-side fix or put a workaround in Sabre ?

**Comment by evert** [comment]
I'm cool with a workaround in sabre/uri.

**Comment by PVince81** [comment]
I tried @Xenopathic's regexp `'/(?:[^[:ascii:]]|:)/u',` and it seems to match colons fine and also non-ascii chars. I'll prepare a PR.

**Comment by PVince81** [comment]
Argh, looks like this would break other cases where the URL is absolute: "http://..." would also encode the colon. And since we haven't parsed the URL yet we can't know which part is the path... Chicken-egg.

Another is then to do another regexp that only replaces the colon only if it appears after any first slash in the string.

What do you think ?

**Comment by staabm** [comment]
> Another is then to do another regexp that only replaces the colon only if it appears after any first slash in the string.

not sure we support this, but colons can also appear as a `username:password` pair within the host portion.

**Comment by PVince81** [comment]
PR here https://github.com/fruux/sabre-uri/pull/12
